# See https://docs.docker.com/compose/compose-file/
version: '2'

services:

  nginx:
    build: ./nginx
    image: lingdb/nginx
    depends_on:
     - cobl
     - sndcomp
    links:
     - cobl
     - sndcomp
    volumes:
     - ${DOCKER_BASE}/nginx/sound:/sound
     - ${DOCKER_BASE}/CoBL/stage1/CoBL/static:/ielexStatic
    ports:
     - "80:80"
    network_mode: "bridge"

  cobl:
    image: lingdb/cobl_stage2
    links:
     - postgres
    network_mode: "bridge"
    volumes:
     - ${DOCKER_BASE}/CoBL/stage1/CoBL:/CoBL
    depends_on:
     - postgres

  sndcomp:
    image: lingdb/sndcomp.php
    links:
     - mariadb
    network_mode: "bridge"
    depends_on:
     - mariadb

  mariadb:
    build: ./mariadb
    image: lingdb/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: 'v4'
    network_mode: "bridge"

  mariadb_backup:
    build: ./mariadb/backup
    image: lingdb/mariadb_backup
    links:
     - mariadb:mysql
    environment:
      MYSQL_ROOT_PASSWORD: '$MYSQL_ROOT_PASSWORD'
    volumes:
     - ${DOCKER_BASE}/mariadb/backup:/backup
    network_mode: "bridge"
    depends_on:
     - mariadb

  postgres:
    build: ./postgres
    image: lingdb/postgres
    environment:
      POSTGRES_PASSWORD: '$POSTGRES_PASSWORD'
      POSTGRES_USER: 'ielexuser'
    network_mode: "bridge"

  postgres_backup:
    build: ./postgres/backup
    image: lingdb/postgres_backup
    links:
     - postgres
    environment:
      PGPASSWORD: '$POSTGRES_PASSWORD'
    volumes:
     - ${DOCKER_BASE}/postgres/backup:/backup
    network_mode: "bridge"
    depends_on:
     - postgres
