# See https://docs.docker.com/compose/compose-file/
version: '2'

services:

  nginx:
    container_name: lingdb_nginx
    build: ./nginx
    image: lingdb/nginx
    depends_on:
      - cobl
      - sndcomp
    links:
      - cobl
      - sndcomp
    volumes:
      - ${DOCKER_BASE}/nginx/sound:/sound
      - /tmp/ielexStatic:/ielexStatic
    ports:
      - 80:80
    network_mode: "bridge"
    restart: unless-stopped
    logging:
      driver: journald

  cobl:
    container_name: lingdb_cobl
    build: ./CoBL
    image: lingdb/cobl
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      DJANGO_SECRET: '${DJANGO_SECRET}'
    volumes:
       - /tmp/ielexStatic:/copyStatic
    network_mode: "bridge"
    restart: unless-stopped
    logging:
      driver: journald

  postgres:
    container_name: lingdb_postgres
    build: ./postgres
    image: lingdb/postgres
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: 'ielexuser'
    network_mode: "bridge"
    restart: unless-stopped
    logging:
      driver: journald

  postgres_backup:
    container_name: lingdb_postgres_backup
    build: ./postgres/backup
    image: lingdb/postgres_backup
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      PGPASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - ${DOCKER_BASE}/postgres/backup:/backup
    network_mode: "bridge"
    restart: unless-stopped
    logging:
      driver: journald

  postgres_create:
    container_name: lingdb_postgres_create
    build: ./postgres/create
    image: lingdb/postgres_create
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      PGPASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - ${DOCKER_BASE}/postgres/create:/create
    network_mode: "bridge"
    logging:
      driver: journald

  sndcomp:
    container_name: lingdb_sndcomp
    build: ./sndcomp.php
    image: lingdb/sndcomp.php
    depends_on:
      - mariadb
    links:
      - mariadb
    network_mode: "bridge"
    restart: unless-stopped
    logging:
      driver: journald

  mariadb:
    container_name: lingdb_mariadb
    build: ./mariadb
    image: lingdb/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: 'v4'
    network_mode: "bridge"
    restart: unless-stopped
    logging:
      driver: journald

  mariadb_backup:
    container_name: lingdb_mariadb_backup
    build: ./mariadb/backup
    image: lingdb/mariadb_backup
    depends_on:
      - mariadb
    links:
      - mariadb
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    volumes:
      - ${DOCKER_BASE}/mariadb/backup:/backup
    network_mode: "bridge"
    restart: unless-stopped
    logging:
      driver: journald

  mariadb_create:
    container_name: lingdb_mariadb_create
    build: ./mariadb/create
    image: lingdb/mariadb_create
    depends_on:
      - mariadb
    links:
      - mariadb:mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    volumes:
      - ${DOCKER_BASE}/mariadb/create:/create
    network_mode: "bridge"
    logging:
      driver: journald
