FROM ubuntu:latest

MAINTAINER Jakob Runge <mam09crm@studserv.uni-leipzig.de>

RUN apt-get install -y \
    python-virtualenv \
    python-pip \
    build-essential \
    python-dev \
    libmysqlclient-dev \
    pwgen git
