FROM mariadb:latest

MAINTAINER Jakob Runge <mam09crm@studserv.uni-leipzig.de>

LABEL lingdb="mariadb" \
      version="1.0.1" \
      documentation="https://github.com/lingdb/container/wiki/mariadb"
