FROM postgres:9.3.10

MAINTAINER Jakob Runge <mam09crm@studserv.uni-leipzig.de>

LABEL lingdb="postgres" \
      version="1.0.0" \
      documentation="https://github.com/lingdb/container/wiki/postgres"
